sudo: required
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker pull adzo261/express-cicd
  - docker run --name adzo261-express-cicd -p 80:3000 -d adzo261/express-cicd
  - docker ps -a

script:
  - docker run adzo261/express-cicd npm run test

#after_success:

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "express-cicd"
  env: "ExpressCicd-env"
  bucket_name: "elasticbeanstalk-us-east-1-601011524156"
  bucket_path: "docker-web-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
