sudo: required
services:
  - docker

before_install:
  - docker build -t adzo261/express-cicd -f Dockerfile .

script:
  - docker run adzo261/express-cicd npm run test

after_success:
  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take built images and push to DOcker hub
  - docker push adzo261/express-cicd

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "express-cicd"
  env: "ExpressCicd-env"
  bucket_name: "elasticbeanstalk-us-east-1-601011524156"
  bucket_path: "express-cicd"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
